version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 7000
    volumes:
      - ./web:/usr/share/nginx/html
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./db-data:/var/lib/postgresql/data
